In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import fpfs
import fitsio
import lensPT as lpt

In [3]:
cat=lpt.observable.Catalog('./fpfs-cut32-0000-g1-0000.fits',mode_names=['fpfs_M00', 'fpfs_M22c'])
nms=[
    "fpfs_M00",
    "fpfs_M20",
    "fpfs_M22c",
    "fpfs_M22s",
    "fpfs_M40",
    "fpfs_M42c",
    "fpfs_M42s",
]
cat=lpt.observable.Catalog('./fpfs-cut32-0000-g1-0000.fits', mode_names=nms)

In [4]:
data=fitsio.read('./fpfs-cut32-0000-g1-0000.fits')
ell_fpfs=fpfs.catalog.fpfsM2E(data, const=1., noirev=False)

In [23]:
ell1=lpt.fpfs.weighted_e1(Const=1.)
np.testing.assert_array_almost_equal(ell1.evaluate(cat), ell_fpfs['fpfs_e1'])

ell2=lpt.fpfs.weighted_e2(Const=1.)
np.testing.assert_array_almost_equal(ell2.evaluate(cat), ell_fpfs['fpfs_e2'])

In [24]:
de1_dg=lpt.shear.g1_perturb1(ell1)
np.testing.assert_array_almost_equal(de1_dg.evaluate(cat), ell_fpfs['fpfs_R1E'])
de2_dg=lpt.shear.g2_perturb1(ell2)
np.testing.assert_array_almost_equal(de2_dg.evaluate(cat), ell_fpfs['fpfs_R2E'])

In [26]:
lpt.shear.g2_perturb1(ell1).evaluate(cat)

DeviceArray([-2.0443629e-02, -1.9980099e-02,  3.8605412e-03,
              8.9093698e-03,  3.8315693e-03, -3.1614301e-04,
             -1.4659713e-03, -1.6872744e-03, -3.5665513e-03,
              5.4947715e-03,  1.4362693e-03,  3.8454324e-02,
              4.1667387e-02,  6.4823106e-02, -4.8193251e-04,
             -6.2746005e-03, -8.2711643e-03,  6.2288171e-05,
             -6.3474476e-03,  4.9076444e-03, -2.0742211e-02,
             -2.6656084e-03, -3.1420225e-03, -1.3198294e-02,
             -2.0027472e-02,  1.2632523e-04,  8.0843242e-03,
              2.9222539e-04,  7.2754879e-04,  4.6913136e-02],            dtype=float32)

array([0.5365309 , 0.60073639, 0.55466984, 0.51822383, 0.20568703,
       0.22068772, 0.60877123, 0.4925861 , 0.19432963, 0.39988843,
       0.35168683, 0.03258118, 0.01764065, 0.06337552, 0.38181768,
       0.43415663, 0.19165998, 0.68620104, 0.25074342, 0.1636867 ,
       0.51826924, 0.29986489, 0.28027197, 0.77126594, 0.51615504,
       0.04816369, 0.41815881, 0.2314344 , 0.28864829, 0.22434546])

In [19]:
ell1.grad(cat)[:,2]

DeviceArray([0.19617349, 0.19978626, 0.12464886, 0.12476494, 0.17730156,
             0.17360353, 0.18234405, 0.17824766, 0.04698408, 0.08552601,
             0.05247934, 0.10805685, 0.10582086, 0.10381842, 0.02944354,
             0.0295583 , 0.10027365, 0.02886714, 0.10028466, 0.14047427,
             0.01404144, 0.0938367 , 0.11277071, 0.13327485, 0.13354631,
             0.190909  , 0.19802819, 0.09716644, 0.01391387, 0.18941315],            dtype=float32)

In [14]:
cat.mode_names

['fpfs_M00',
 'fpfs_M20',
 'fpfs_M22c',
 'fpfs_M22s',
 'fpfs_M40',
 'fpfs_M42c',
 'fpfs_M42s']

In [20]:
1./(cat.data[:,0]+1.)

array([0.19617348, 0.19978626, 0.12464886, 0.12476494, 0.17730155,
       0.17360353, 0.18234405, 0.17824766, 0.04698408, 0.08552601,
       0.05247934, 0.10805685, 0.10582086, 0.10381842, 0.02944354,
       0.0295583 , 0.10027365, 0.02886714, 0.10028466, 0.14047428,
       0.01404144, 0.0938367 , 0.11277071, 0.13327485, 0.13354631,
       0.190909  , 0.19802819, 0.09716644, 0.01391387, 0.18941314])