In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import jax
import jax.numpy as jnp
from flax import struct
from jax.tree_util import tree_flatten
import gimpt
from gimpt.fpfs import *
from gimpt.fpfs.default_fpfs import *

ndat=1
a = jnp.zeros((2, ncol))
a=a.at[:, m00].set(4)
a=a.at[:, m22c].set(1)

params = FpfsParams(Const=2.0)
e1F = FpfsE1(params)

No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)


In [8]:
%time e1_res=gimpt.RespG1(e1F)

CPU times: user 170 µs, sys: 128 µs, total: 298 µs
Wall time: 309 µs


In [9]:
%time e1_res.evaluate(a)

CPU times: user 86.6 ms, sys: 1.3 ms, total: 87.9 ms
Wall time: 82.9 ms


Array([0.51068823, 0.51068823], dtype=float64)

In [10]:
%time e1F.hessian(a).shape

CPU times: user 116 ms, sys: 2.23 ms, total: 118 ms
Wall time: 114 ms


(2, 31, 31)

In [6]:
e1F2=e1F*2

In [7]:
e1F2.hessian(a).shape

(2, 31, 31)

In [10]:
sres= gimpt.FpfsModeResponse()
sres.dg1(a).shape

AttributeError: module 'gimpt' has no attribute 'FpfsModeResponse'

In [ ]:
jax.vmap(jax.grad(gimpt.pt.ptshear(op_fpfs.e1, sres._dg1_row)))(a).M00

In [6]:
jax.lax.map(op_fpfs.e1, a)

Array([0.2, 0.2], dtype=float64)

In [14]:
op_fpfs.e1(a)

Array([0.2, 0.2], dtype=float64)

In [23]:
xgrad(op_fpfs.e1)(a).shape

(2, 15)

In [6]:
gimpt.pt.ptshear(op_fpfs.e1, gimpt.lin.shapelets_dg1)(a)

Array([0.62225397, 0.62225397], dtype=float64)