In [2]:
%reload_ext autoreload
%autoreload 2

In [7]:
import jax
import jax.numpy as jnp
from flax import struct
from jax.tree_util import tree_flatten
import gimpt
from gimpt.fpfs import *
from gimpt.fpfs.default_fpfs import *

ndat=1
a = jnp.zeros((2, ncol))
a=a.at[:, m00].set(4)
a=a.at[:, m22c].set(1)

params = FpfsParams(Const=2.0)
e1F = FpfsE1(params)

In [ ]:
gimpt.

In [4]:
e1F.hessian(a).shape

(2, 31, 31)

In [5]:
e1F2=e1F*2

In [6]:
e1F2.hessian(a).shape

(2, 31, 31)

In [ ]:
a=2

In [7]:
type(a)

int

In [8]:
type(e1F)

gimpt.nlobs.FpfsE1

In [9]:
isinstance(a, float)

False

In [10]:
sres= gimpt.FpfsModeResponse()
sres.dg1(a).shape

AttributeError: module 'gimpt' has no attribute 'FpfsModeResponse'

In [ ]:
jax.vmap(jax.grad(gimpt.pt.ptshear(op_fpfs.e1, sres._dg1_row)))(a).M00

In [6]:
jax.lax.map(op_fpfs.e1, a)

Array([0.2, 0.2], dtype=float64)

In [14]:
op_fpfs.e1(a)

Array([0.2, 0.2], dtype=float64)

In [23]:
xgrad(op_fpfs.e1)(a).shape

(2, 15)

In [6]:
gimpt.pt.ptshear(op_fpfs.e1, gimpt.lin.shapelets_dg1)(a)

Array([0.62225397, 0.62225397], dtype=float64)