In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
fitsio.read('../../data/fpfs-cut32-0000-g1-0000.fits').dtype.names

NameError: name 'fitsio' is not defined

In [3]:
import jax
import jax.numpy as jnp
import fitsio

import impt
from impt.fpfs import *
from impt.fpfs.default import *

ndat=1
a = jnp.zeros((2, ncol))
a=a.at[:, m00].set(4)
a=a.at[:, m22c].set(1)

params = FpfsParams(Const=2.0)
e1F = FpfsE1(params)

No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)


In [6]:
read_catalog('../../data/fpfs-cut32-0000-g1-0000.fits')

Array([[ 4.09752893e+00, -2.88539934e+00, -4.26928043e-01,
         8.79848123e-01,  3.01192701e-01,  9.30899903e-02,
        -6.81932569e-01,  2.77866721e-01,  1.23747438e-01,
         9.21800807e-02,  1.77183792e-01,  2.38777801e-01,
         2.66482353e-01,  3.43591034e-01,  3.77921879e-01,
        -2.39462614e-01, -6.25913069e-02,  2.07771838e-01,
        -4.36694361e-02, -2.40804300e-01,  1.35118037e-01,
         3.98086548e-01,  8.70893300e-02, -3.52623582e-01,
        -3.31814051e-01, -1.81829184e-01, -1.09329894e-02,
         1.76746637e-01,  1.86438203e-01, -2.31516771e-02,
        -2.51008660e-01],
       [ 4.00534916e+00, -2.75232530e+00, -4.99926090e-01,
         7.08020151e-01, -1.47179469e-01, -2.94191507e-03,
        -4.49338198e-01,  1.98130399e-01,  3.67237359e-01,
         5.05870879e-01,  5.07652581e-01,  3.10716897e-01,
         2.43288521e-02, -9.21800807e-02,  1.69463288e-02,
        -1.87041178e-01,  5.03020100e-02,  3.53864700e-01,
         1.11029290e-01, -2.94

In [3]:
%time e1_res=impt.RespG1(e1F)

CPU times: user 614 µs, sys: 0 ns, total: 614 µs
Wall time: 633 µs


In [4]:
%time e1_res.evaluate(a)

CPU times: user 130 ms, sys: 6.23 ms, total: 136 ms
Wall time: 131 ms


Array([0.51068823, 0.51068823], dtype=float64)

In [10]:
%time e1F.hessian(a).shape

CPU times: user 116 ms, sys: 2.23 ms, total: 118 ms
Wall time: 114 ms


(2, 31, 31)

In [6]:
e1F2=e1F*2

In [7]:
e1F2.hessian(a).shape

(2, 31, 31)

In [10]:
sres= gimpt.FpfsModeResponse()
sres.dg1(a).shape

AttributeError: module 'gimpt' has no attribute 'FpfsModeResponse'

In [ ]:
jax.vmap(jax.grad(gimpt.pt.ptshear(op_fpfs.e1, sres._dg1_row)))(a).M00

In [6]:
jax.lax.map(op_fpfs.e1, a)

Array([0.2, 0.2], dtype=float64)

In [14]:
op_fpfs.e1(a)

Array([0.2, 0.2], dtype=float64)

In [23]:
xgrad(op_fpfs.e1)(a).shape

(2, 15)

In [6]:
gimpt.pt.ptshear(op_fpfs.e1, gimpt.lin.shapelets_dg1)(a)

Array([0.62225397, 0.62225397], dtype=float64)