In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import jax
import jax.numpy as jnp
import fitsio

import impt
from impt.fpfs import *
from impt.fpfs.default import *

test_fname = os.path.join(
    impt.fpfs.__data_dir__,
    "fpfs-cut32-0000-g1-0000.fits",
    )


ndat=1
a = jnp.zeros((2, ncol))
a=a.at[:, m00].set(4)
a=a.at[:, m22c].set(1)
a=read_catalog(test_fname)

params = FpfsParams(Const=2.0)
e1F = FpfsE1(params)

No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)


In [3]:
%time e1_res=impt.RespG1(e1F)

CPU times: user 389 µs, sys: 0 ns, total: 389 µs
Wall time: 405 µs


In [4]:
%time e1_res.evaluate(a)

CPU times: user 118 ms, sys: 6.9 ms, total: 125 ms
Wall time: 119 ms


Array([0.44717932, 0.49874483, 0.49314654, 0.46044914, 0.17423632,
       0.18803906, 0.51060362, 0.41078727, 0.1854596 , 0.367104  ,
       0.33412746, 0.02760837, 0.01336256, 0.05334877, 0.37088438,
       0.42157247, 0.17327798, 0.66694222, 0.22701669, 0.14226512,
       0.5109574 , 0.27400206, 0.25169579, 0.67674468, 0.45296912,
       0.02898522, 0.3466351 , 0.21092493, 0.28451688, 0.17119237],      dtype=float64)

In [10]:
%time e1F.hessian(a).shape

CPU times: user 116 ms, sys: 2.23 ms, total: 118 ms
Wall time: 114 ms


(2, 31, 31)

In [6]:
e1F2=e1F*2

In [7]:
e1F2.hessian(a).shape

(2, 31, 31)

In [10]:
sres= gimpt.FpfsModeResponse()
sres.dg1(a).shape

AttributeError: module 'gimpt' has no attribute 'FpfsModeResponse'

In [ ]:
jax.vmap(jax.grad(gimpt.pt.ptshear(op_fpfs.e1, sres._dg1_row)))(a).M00

In [6]:
jax.lax.map(op_fpfs.e1, a)

Array([0.2, 0.2], dtype=float64)

In [14]:
op_fpfs.e1(a)

Array([0.2, 0.2], dtype=float64)

In [23]:
xgrad(op_fpfs.e1)(a).shape

(2, 15)

In [6]:
gimpt.pt.ptshear(op_fpfs.e1, gimpt.lin.shapelets_dg1)(a)

Array([0.62225397, 0.62225397], dtype=float64)